// src/Svelte/FunctionPropItem.svelte

<script>
    import {createEventDispatcher} from 'svelte'
    const dispatch = createEventDispatcher();
    export let onAlert

    function innerOnAlert () {
        dispatch('onAlert2', {
            text: 'Svelte2',
            value: 'Svelte Emit'
        })
    }
</script>

<button value="Svelte" on:click={(e) => onAlert('Svelte', e)}>alert 호출</button>
<button value="Svelte2" on:click={innerOnAlert}>alert 호출 2</button>
<button on:click={(e) => console.log("inner instance test")}>inner instance test</button>
<button on:click="{(e) => console.log('inner instance test2')}">inner instance test2</button>

// src/Vue/FunctionPropItem.vue
<template>
  <div>
    <button value="Vue" @click="$emit('onAlert', 'Vue Alert', $event)">alert 호출하기</button>
    <button value="Vue2" @click="(e)=>onAlert2('Vue2', e)">alert 호출하기2</button>
<!--    //<div @click="(e) => alert('aa')">text</div> vm에 alert가 없으므로 alert가 동작하지 않음.-->
  </div>
</template>

<script>
export default {
  name: "FunctionPropItem",
  props: {
    onAlert2: Function
  },

}
</script>
